[package]
name = "rukki"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.10"
clap = { version = "4.1", features = ["derive"] }
os_str_bytes = "6.1.*"